line.bot:
  channel-token: '2FlCfp4wiiiYbbPe0g0boCGYJ3GvAaTgrR8xiA/aFuewnT1DCY1XjNM9qyBwjaX1T/XJv/lBcKglBEz9nNxnEuCEbLLHfJazQlqvoiKxTMc8BZq/IoqaWBqojZ6WX3lQxdurIj3iF2SfaGmjmDdmMAdB04t89/1O/w1cDnyilFU='
  channel-secret: '641582e53e2f62cb412b59b7759048f4'
  handler.path: /linebot
